### ISSUE TITLE
unaccessable website

### ISSUE THREAD

**Issue by JiYuanFeng** [BCV-Uniandes/Bonet#1]
Hi, Thank you for your great contribution to the bone age assessment, and we want to access this dataset, however, the website rejects our assessment. I want to how can I access this public dataset? 
Thank you very much

**Comment by lydials** [comment]
The same question.

**Comment by chenchao666** [comment]
The same question, I can not access the download webpage

**Comment by mc-escobar11** [comment]
Hi, thank you for being interested in our contribution. You can access the RHPE dataset and all the other Bone Age Assessment resources through this  [link](http://malik.uniandes.edu.co/baar/). 
Please let us know if you have any other question.

**Comment by lydials** [comment]
> Hi, thank you for being interested in our contribution. You can access the RHPE dataset and all the other Bone Age Assessment resources through this [link](http://malik.uniandes.edu.co/baar/).
> Please let us know if you have any other question.

It works. Thanks.

**Comment by dakun333** [comment]
> Hi, Thank you for your great contribution to the bone age assessment, and we want to access this dataset, however, the website rejects our assessment. I want to how can I access this public dataset?
> Thank you very much

可以将RHPE数据分享给我一份么，谢谢；m15326861966@163.com

**Comment by dochenms** [comment]
@mc-escobar11 the issue appeared again, can you provide one new link?
