### ISSUE TITLE
How to reproduce results on test set?

### ISSUE THREAD

**Issue by lydials** [BCV-Uniandes/Bonet#2]
Thanks for your work. 

I notice that BoNet requires ROI annotations during inference, but the ROI annotations are not provided for both RSNA and RHPE test sets ([at here](http://malik.uniandes.edu.co/baar/dataset)). Can you share these files?

**Comment by mc-escobar11** [comment]
Hello, we have added the Anatomical ROIs annotations. You can check them out [here](http://malik.uniandes.edu.co/baar/dataset). Let us know if you have other questions
