### ISSUE TITLE
Could you tell me how you caculate OKS in your paper: Hand Pose Estimation for Pediatric Bone Age Assessment.

### ISSUE THREAD

**Issue by Annnnmmmm** [BCV-Uniandes/Bonet#6]
I can't find the supplementary material that provides the method of computing sigma in OKS. Could you please tell me how to do it.

**Comment by mc-escobar11** [comment]
Hi, you can access the supplementary material through this [link](https://biomedicalcomputervision.uniandes.edu.co/wp-content/uploads/2021/06/Hand_Pose_Sup.pdf)
